from selenium.webdriver.common.by import By

class Locators:
    LOGIN_TAB = (By.XPATH, ".//button[text() = 'Войти в аккаунт']")
    Email = (By.XPATH, ".//input[@name='name']")
    PASSWORD = (By.XPATH, ".//input[@name = 'Пароль']")
    LOGIN_BUTTON = (By.XPATH, ".//button[text() = 'Войти']")
    LOGIN_VIA_REG = (By.XPATH, ".//a[text() = 'Войти']")
    ORDER_BUTTON = (By.XPATH, ".//button[text() = 'Оформить заказ']")
    PERSONAL_AREA = (By.XPATH, ".//p[text() = 'Личный Кабинет']")
    SAVE_BUTTON = (By.XPATH, ".//button[text() = 'Сохранить']")
    EXIT_BUTTON = (By.XPATH, ".//button[text() = 'Выход']")
    DESIGNER_BUTTON = (By.XPATH, ".//p[text() = 'Конструктор']")
    LOGO_BUTTON = (By.XPATH, ".//div[@class = 'AppHeader_header__logo__2D0X2']")
    REGISTER_BUTTON = (By.XPATH, ".//button[text()='Зарегистрироваться']")
    NAME_REG = (By.XPATH, ".//label[text()='Имя']/following-sibling::input")
    Email_REG = (By.XPATH, ".//label[text()='Email']/following-sibling::input")
    REG_BUTTON = (By.XPATH, ".//a[text()='Зарегистрироваться']")
    INFO = (By.XPATH, ".//p[text() = 'В этом разделе вы можете изменить свои персональные данные']")
    INCORRECT_PASSWORD =(By.XPATH, ".//p[text() = 'Некорректный пароль']")
    SAUSES_BUTTON = (By.XPATH, ".//span[text()='Соусы']")
    SPICY = (By.XPATH, ".//img[@alt = 'Соус Spicy-X']")
    FILLINGS_BUTTON = (By.XPATH, ".//span[text()='Начинки']")
    CHOP_BUTTON = (By.XPATH, ".//img[@alt = 'Говяжий метеорит (отбивная)']")
    BOOKLET_BUTTON = (By.XPATH, ".//span[text()='Булки']")
    FLUORESENT_BUN = (By.XPATH, ".//img[@alt = 'Флюоресцентная булка R2-D3']")
    SAUSES_BUTTON_PARENT =(By.XPATH, ".//span[text() = 'Соусы']/parent::div")
    FILLINGS_BUTTON_PARENT = (By.XPATH, ".//span[text() = 'Начинки']/parent::div")
    BOOKLET_BUTTON_PARENT = (By.XPATH, ".//span[text() = 'Булки']/parent::div")